application: steam-screenshots
version: 1
runtime: python27
api_version: 1
threadsafe: true

#------------------------------------------------------------------------------

skip_files:
-   ^(.*/)?.*\.py[co]$
-   ^cache(.*)$

#------------------------------------------------------------------------------

handlers:

-   url:        /static
    static_dir: static

-   url:        /scraper/.+
    script:     urls.application
    login:      admin

-   url:        .*
    script:     urls.application

#------------------------------------------------------------------------------

libraries:

-   name: webapp2
    version: latest

-   name: jinja2
    version: latest
