application: steam-screenshots
version: 1
runtime: python27
api_version: 1
threadsafe: true



handlers:

-   url: /.*
    script: main.application

-   url: /static
    static_dir: static



libraries:

-   name: webapp2
    version: latest

-   name: jinja2
    version: latest